#ifndef CONFIGURATION_H_
#define CONFIGURATION_H_

#include "driver/gpio.h"

#define TRAFFIC_LIGHT_RED_LED_GPIO GPIO_NUM_18
#define TRAFFIC_LIGHT_YELLOW_LED_GPIO GPIO_NUM_16
#define TRAFFIC_LIGHT_GREEN_LED_GPIO GPIO_NUM_4
#define TRAFFIC_LIGHT_MODE_BUTTON_GPIO GPIO_NUM_5

#define TRAFFIC_LIGHT_TIMER_RESOLUTION_HZ 1000000U /* 1 tick = 1 us */

#define TRAFFIC_LIGHT_GREEN_DURATION_MS 5000U
#define TRAFFIC_LIGHT_GREEN_BLINK_DURATION_MS 3500U
#define TRAFFIC_LIGHT_YELLOW_DURATION_MS 2000U
#define TRAFFIC_LIGHT_RED_DURATION_MS 5000U
#define TRAFFIC_LIGHT_RED_YELLOW_DURATION_MS 1000U
#define TRAFFIC_LIGHT_BLINK_INTERVAL_MS 500U
#define TRAFFIC_LIGHT_BUTTON_DEBOUNCE_US 40000U

#define TRAFFIC_LIGHT_PROCESS_INTERVAL_MS 10U

#endif // CONFIGURATION_H_